### PR TITLE
fix: support mv3 background script

### PR DESCRIPTION
**Pull request by iantanwx**
[//]: # (Briefly describe what your PR is about and/or solves.)

Fixes background worker issues in manifest version 3. See https://github.com/rubenspgcavalcante/webpack-extension-reloader/pull/139.

#### Checklist

- [x] I ran the linting and formatting tools (ESLint and Prettier)
- [x] I added addittional tests if adding new features

Closes #[ISSUE_NUMBER]

### CODE REVIEW

**Comment by ralphschindler** [comment]
Hi! Any movement on getting this PR in master? Thanks :D

**Comment by bashbaugh** [comment]
Hey! I'm looking for this as well, can it be merged?

**Comment by lucasrmendonca** [comment]
Hi @rushilsrivastava @rubenspgcavalcante could you help to review this PR?

**Comment by just-jeb** [comment]
I tried both this patch and #220, non of them seem to be working. Getting `Service worked registration failed` with `Uncaught TypeError: Cannot read properties of null (reading 'runtime')` because `browser` is `null`.

**Comment by iantanwx** [comment]
> I've tried both this patch and #220, none of them seem to be working. Getting `Service worked registration failed` with `Uncaught TypeError: Cannot read properties of null (reading 'runtime')` because `browser` is `null`.

that's really odd -- it works in our fork. could you try that and see?

**Comment by rushilsrivastava** [comment]
Sorry for the hiatus - happy to help get this merged in. 

> I've tried both this patch and #220, none of them seem to be working. Getting `Service worked registration failed` with `Uncaught TypeError: Cannot read properties of null (reading 'runtime')` because `browser` is `null`.

Any reproducible examples?

**Comment by rushilsrivastava** [comment]
@iantanwx Were you able to reproduce this?

**Comment by iantanwx** [comment]
> 

Sorry I have been really busy, have not rebased upstream yet. Will try to do this in the coming week. Apologies!

**Comment by riverajohan** [comment]
Having this merges would be very helpful 🥇

**Comment by lucasrmendonca** [comment]
Hi @iantanwx any news on this?

**Comment by sherifmayika** [comment]
> I've tried both this patch and #220, none of them seem to be working. Getting `Service worked registration failed` with `Uncaught TypeError: Cannot read properties of null (reading 'runtime')` because `browser` is `null`.

I can give you a clue to how to solve this issue. browser.runtime should be replaced with chrome.runtime in manifest 3. 
for example: open: webpack-ext-reloader.js from  '/node_modules/webpack-ext-reloader/dist'  replace "browser.extension", "browser.runtime", with "chrome.extension" and "chrome.extension" . Origin of this error is from 'webextension-polyfill'.  I think 'webextension-polyfill' lack support for manifest 3.

**Comment by reorx** [comment]
I adapted @sherifmayika 's advice and finally made my fork work. Anyone with the same problem can try to use my fork at https://github.com/reorx/webpack-ext-reloader

**Comment by rushilsrivastava** [comment]
Perfect, I'll take a look at the PR @reorx!

**Comment by vialoh** [comment]
Closing in favor of #386.

**Pull request closed without merging**
